/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:3bbe163e-8dbf-4e5e-ab3a-28443113d4b8",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_N2ooTya0d",
    "aws_user_pools_web_client_id": "cki4tbosd2qfv36t33up7u59n",
    "oauth": {
        "domain": "tempo-video-portfolio.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://tempo-video.com/portfolio/",
        "redirectSignOut": "https://tempo-video.com/portfolio/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
